Implemented search for lots and pagination
htmlacademy-php/43436-yeticave-12 pull request #14
Opened 2021-10-19 19:23 UTC by katesheleh

2021-10-20 21:07 UTC, zenoleg reviewed
Все просто офигенно, лишь по мелочи незначительной

2021-10-20 21:07 UTC, zenoleg commented on helpers/fetchers.php
> +        $searchResultArray = explode(' ', $searchString);
До этого там может быть куча пробелов, в итоге может выйти, что получится что-то вроде крепления * * * * * * * * DC

2021-10-20 21:07 UTC, zenoleg commented on helpers/fetchers.php
> +        $searchResultArray = explode(' ', $searchString);
Давай заменим двойные пробелы на одинарные и сделаем trim()

2021-10-20 21:07 UTC, zenoleg commented on helpers/fetchers.php
> +            "' IN BOOLEAN MODE);";
Можно было и без BOOLEAN MODE, но рад, что решила его пощупать.
тут все ок 🔥

2021-10-20 21:07 UTC, zenoleg commented on templates/search-template.php
> +                <!-- count($searchResult) === 0 -->
дебаг стоит убрать потом)

2021-10-20 21:48 UTC, zenoleg requested changes

2021-10-20 21:48 UTC, zenoleg commented on search.php
> +        $lotsPerPage = 3;
> Под заголовком находится список из девяти активных лотов, найденных по поисковому запросу. Лоты отсортированы по дате публикации, от новых к старым. Если в категории больше девяти лотов, то внизу страницы появляется блок постраничной навигации.

2021-10-21 16:09 UTC, katesheleh commented on helpers/fetchers.php
> +        $searchResultArray = explode(' ', $searchString);
Смотри, я здесь проверяю if(strlen($searchItem) > 0), у меня так получается без пустых звездочек. Этот вариант подходит?

2021-10-21 21:15 UTC, merged